### ISSUE TITLE
Spacing problems with _includes/head-custom.html

### ISSUE THREAD

**Issue by pippim** [pages-themes/merlot#12]
The file `_includes/head-custom.html` contains:

``` html
<!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->
{% include head-custom-google-analytics.html %}

<!-- Buttons to appear top of every page -->
<div class="container">
  <a href="https://pippim.github.io/" style="display: inline" class="button">Home</a>
  <a href="about.html" style="display: inline" class="button">About pippim</a>
  <a href="answers.html" style="display: inline" class="button">Answers</a>
  <a href="programs.html" style="display: inline" class="button">Programs</a>
</div>

<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="{{ '/favicon.ico' | relative_url }}" -->

<!-- end custom head snippets -->
```

### Image

The buttons are breaking up the Merlot rendering:

![About pippim](https://user-images.githubusercontent.com/92641463/138567216-92b0ffc2-90a2-46c8-a468-e679d83196f0.png)

Can buttons be moved lower or at least not break up Merlot's original background?

### CSS

If it helps here is `assets/css/style.scss`:

``` css
---
---

@import "{{ site.theme }}";

//                    Pure CSS Button Hover effect
// From: https://www.sliderrevolution.com/resources/css-button-hover-effects/

$color: #0cf;

.button {
  display: inline-block;
  padding: .75rem 1.25rem;
  border-radius: 10rem;
  color: #fff;
  // text-transform: uppercase;
  // font-size: 1rem;
  // letter-spacing: .15rem;
  transition: all .3s;
  position: relative;
  overflow: hidden;
  z-index: 1;
  &:after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: $color;
    border-radius: 10rem;
    z-index: -2;
  }
  &:before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 0%;
    height: 100%;
    background-color: darken($color, 15%);
    transition: all .3s;
    border-radius: 10rem;
    z-index: -1;
  }
  &:hover {
    color: #fff;
    &:before {
      width: 100%;
    }
  }
}

/* optional reset for presentation
* {
  font-family: Arial;
  text-decoration: none;
  font-size: 20px;
}
 */

.container {
  padding-top: 50px;
  margin: 0 auto;
  width: 100%;
  text-align: center;
}
h1 {
  text-transform: uppercase;
  font-size: .8rem;
  margin-bottom: 2rem;
  color: #777;
}
span {
  display: block;
  margin-top: 2rem;
  font-size: .7rem;
  color: #777;
  a {
    font-size: .7rem;
    color: #999;
    text-decoration: underline;
  }
}
```
